In [95]:
# Dependencies
import pandas as pd
import csv
import os
from numpy import nan
# Store filepath in a variable
happiness_df = pd.read_csv("2016happiness.csv", encoding="ISO-8859-1")

In [96]:
# Store filepath in a variable
happiness_df = pd.read_csv("2016happiness.csv", encoding="ISO-8859-1")

In [97]:
#preview data
happiness_df.head()
happiness_df['Country'].sort_values(ascending=True)

153               Afghanistan
108                   Albania
37                    Algeria
140                    Angola
25                  Argentina
120                   Armenia
8                   Australia
11                    Austria
80                 Azerbaijan
41                    Bahrain
109                Bangladesh
60                    Belarus
17                    Belgium
51                     Belize
152                     Benin
83                     Bhutan
58                    Bolivia
86     Bosnia and Herzegovina
136                  Botswana
16                     Brazil
128                  Bulgaria
144              Burkina Faso
156                   Burundi
139                  Cambodia
113                  Cameroon
5                      Canada
143                      Chad
23                      Chile
82                      China
30                   Colombia
                ...
57                South Korea
142               South Sudan
36                      Spain
116                 Sri Lanka
132                     Sudan
39                   Suriname
9                      Sweden
1                 Switzerland
155                     Syria
34                     Taiwan
99                 Tajikistan
148                  Tanzania
32                   Thailand
154                      Togo
42        Trinidad and Tobago
97                    Tunisia
77                     Turkey
64               Turkmenistan
145                    Uganda
122                   Ukraine
27       United Arab Emirates
22             United Kingdom
12              United States
28                    Uruguay
48                 Uzbekistan
43                  Venezuela
95                    Vietnam
146                     Yemen
105                    Zambia
130                  Zimbabwe
Name: Country, Length: 157, dtype: object

In [98]:
#dataframe count
happiness_df.shape[0]

157

In [99]:
# Store filepath in a variable
web_access_df = pd.read_csv("web_access.csv", encoding="ISO-8859-1")

In [100]:
#preview data
web_access_df.head()
web_access_df['Country'].sort_values(ascending=True)

0                       Afghanistan
1                           Albania
2                           Algeria
3                           Andorra
4                            Angola
5               Antigua and Barbuda
6                         Argentina
7                           Armenia
8                             Aruba
9                         Australia
10                          Austria
11                       Azerbaijan
12                          Bahamas
13                          Bahrain
14                       Bangladesh
15                         Barbados
16                          Belarus
17                          Belgium
18                           Belize
19                            Benin
20                          Bermuda
21                           Bhutan
22                          Bolivia
23           Bosnia and Herzegovina
24                         Botswana
25                           Brazil
26                           Brunei
27                         Bulgaria
28                     Burkina Faso
29                          Burundi
                   ...
170                           Sudan
171                        Suriname
172                       Swaziland
173                          Sweden
174                     Switzerland
175                           Syria
176                      Tajikistan
177                        Tanzania
179                        Thailand
180                     Timor-Leste
181                            Togo
182                           Tonga
183             Trinidad and Tobago
184                         Tunisia
185                          Turkey
186                    Turkmenistan
189                          Uganda
190                         Ukraine
191            United Arab Emirates
187                  United Kingdom
188                   United States
192    United States Virgin Islands
193                         Uruguay
194                      Uzbekistan
195                         Vanuatu
196                       Venezuela
197                         Vietnam
198                           Yemen
199                          Zambia
200                        Zimbabwe
Name: Country, Length: 201, dtype: object

In [101]:
#dataframe count
web_access_df.shape[0]

201

In [102]:
#merge dataframes using on Country How=left 
combined_df = pd.merge(web_access_df, happiness_df, on="Country",how='left')
#Sort by Country
combined_df['Country'].sort_values(ascending=True)

0                       Afghanistan
1                           Albania
2                           Algeria
3                           Andorra
4                            Angola
5               Antigua and Barbuda
6                         Argentina
7                           Armenia
8                             Aruba
9                         Australia
10                          Austria
11                       Azerbaijan
12                          Bahamas
13                          Bahrain
14                       Bangladesh
15                         Barbados
16                          Belarus
17                          Belgium
18                           Belize
19                            Benin
20                          Bermuda
21                           Bhutan
22                          Bolivia
23           Bosnia and Herzegovina
24                         Botswana
25                           Brazil
26                           Brunei
27                         Bulgaria
28                     Burkina Faso
29                          Burundi
                   ...
170                           Sudan
171                        Suriname
172                       Swaziland
173                          Sweden
174                     Switzerland
175                           Syria
176                      Tajikistan
177                        Tanzania
179                        Thailand
180                     Timor-Leste
181                            Togo
182                           Tonga
183             Trinidad and Tobago
184                         Tunisia
185                          Turkey
186                    Turkmenistan
189                          Uganda
190                         Ukraine
191            United Arab Emirates
187                  United Kingdom
188                   United States
192    United States Virgin Islands
193                         Uruguay
194                      Uzbekistan
195                         Vanuatu
196                       Venezuela
197                         Vietnam
198                           Yemen
199                          Zambia
200                        Zimbabwe
Name: Country, Length: 201, dtype: object

In [105]:
#verify count
combined_df.shape[0]

201

In [106]:
#identify Non Matching Rows
Nulls_df = combined_df[combined_df.isnull().any(axis=1)]
Nulls_df.shape[0]

49

In [107]:
#drop rows with Null Values
Nulls_df

,Country,Internet Users -2016,Penetration (% of Pop),Population-2016,Non-Users (internetless),Users 1 Year Change (%),Internet Users 1 Year Change,Population 1 Y Change,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
3,Andorra,"66,728",96.50%,"69,165","2,437",-1.60%,"-1,059",-1.86%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Antigua and Barbuda,"60,306",65%,"92,738","32,432",1.80%,"1,072",1%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Aruba,"91,532",87.80%,"104,263","12,731",1.80%,"1,609",0.36%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Bahamas,"333,143",84.80%,"392,718","59,575",4.20%,"13,419",1.21%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Barbados,"228,717",80.30%,"285,006","56,289",1.70%,"3,761",0.28%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Bermuda,"60,047",97.40%,"61,662","1,615",-0.30%,-152,-0.55%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Brunei,"310,205",72.30%,"428,874","118,669",2.90%,"8,748",1.34%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Cabo Verde,"224,183",42.50%,"526,993","302,810",2.90%,"6,420",1.25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Cayman Islands,"45,038",74.10%,"60,764","15,726",1.30%,594,1.33%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Central African Republic,"224,432",4.50%,"4,998,493","4,774,061",5.30%,"11,270",2%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Côte d'Ivoire,"5,122,897",22%,"23,254,184","18,131,287",14.30%,"640,961",2.43%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Cuba,"3,696,765",32.40%,"11,392,889","7,696,124",4%,"143,221",0.03%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Djibouti,"105,163",11.70%,"899,598","794,435",4%,"4,050",1.32%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Dominica,"48,249",66.10%,"73,016","24,767",2%,944,0.46%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Equatorial Guinea,"181,657",20.90%,"869,587","687,930",6.10%,"10,384",2.90%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Eritrea,"56,728",1.10%,"5,351,680","5,294,952",4.80%,"2,583",2.37%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Faeroe Islands,"47,515",98.50%,"48,239",724,1.30%,608,0.08%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Fiji,"419,958",46.80%,"897,537","477,579",4%,"16,237",0.60%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,French Polynesia,"182,442",63.90%,"285,735","103,293",2.60%,"4,661",1.05%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Gambia,"346,471",16.90%,"2,054,986","1,708,515",5.70%,"18,830",3.22%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Greenland,"37,899",67.40%,"56,196","18,297",0.40%,135,0.02%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Grenada,"41,675",38.80%,"107,327","65,652",1.60%,670,0.47%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Guam,"124,717",72.50%,"172,094","47,377",2.70%,"3,276",1.30%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Guinea-Bissau,"66,284",3.50%,"1,888,429","1,822,145",4.10%,"2,586",2.39%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Guyana,"305,007",39.60%,"770,610","465,603",2.20%,"6,666",0.46%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Kiribati,"14,724",12.90%,"114,405","99,681",3.30%,472,1.76%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,Lesotho,"444,376",20.60%,"2,160,309","1,715,933",18.10%,"68,128",1.18%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,Liechtenstein,"36,183",95.80%,"37,776","1,593",1%,342,0.65%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,Macao,"433,752",72.60%,"597,126","163,374",2.90%,"12,069",1.62%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Maldives,"198,071",53.60%,"369,812","171,741",4.30%,"8,076",1.69%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,Marshall Islands,"10,709",20.20%,"53,069","42,360",5.60%,565,0.14%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,Micronesia,"32,749",31.20%,"104,966","72,217",2.10%,658,0.48%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Monaco,"35,196",93%,"37,863","2,667",0.70%,228,0.35%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,Mozambique,"1,834,337",6.40%,"28,751,362","26,917,025",5%,"87,863",2.76%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,New Caledonia,"186,502",70%,"266,431","79,929",1.30%,"2,319",1.26%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,Oman,"3,310,260",71.10%,"4,654,471","1,344,211",4.10%,"129,032",3.65%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,Papua New Guinea,"906,695",11.70%,"7,776,115","6,869,420",8.60%,"71,835",2.06%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,Saint Kitts and Nevis,"37,210",66.20%,"56,183","18,973",1.50%,548,1.10%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,Saint Lucia,"109,370",58.70%,"186,383","77,013",5%,"5,189",0.75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,Samoa,"56,373",29%,"194,523","138,150",9.70%,"5,004",0.67%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,Sao Tome and Principe,"49,686",25.60%,"194,390","144,704",3.60%,"1,709",2.13%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,Seychelles,"56,168",57.90%,"97,026","40,858",2.60%,"1,400",0.58%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,Solomon Islands,"58,423",9.80%,"594,934","536,511",4.60%,"2,573",1.94%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,St. Vincent & Grenadines,"65,984",60.20%,"109,644","43,660",2.10%,"1,357",0.17%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,Swaziland,"362,921",27.80%,"1,304,063","941,142",2.20%,"7,667",1.33%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Timor-Leste,"14,030",1.20%,"1,211,245","1,197,215",3.10%,416,2.24%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,Tonga,"49,822",46.60%,"106,915","57,093",5.30%,"2,501",0.70%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,United States Virgin Islands,"57,485",54%,"106,415","48,930",2.40%,"1,357",0.12%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,Vanuatu,"82,764",30.60%,"270,470","187,706",16%,"11,386",2.20%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN